steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "eu.gcr.io/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}:${_TAG}",
        "${_DOCKER_FILE}",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}:${_TAG}"]
