steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "${_DOCKER_FILE}",
        "-t",
        "gcr.io/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}:${_TAG}",
        "${_CONTEXT}",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}:${_TAG}"]
