steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "BASE_IMAGE=${_BASE_IMAGE}",
        "-f",
        "${_DOCKER_FILE}",
        "-t",
         "${_LOCATION}-docker.pkg.dev/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}/${_IMAGE}",
        "${_CONTEXT}",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_LOCATION}-docker.pkg.dev/${_GOOGLE_PROJECT_ID}/${_SERVICE_NAME}/${_IMAGE}"] 
